# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o vm-manager-client
      
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: vm-manager-client
        path: ./vm-manager-client  # Path to the executable you built in the previous step
    
    - name: Tag the repository
      id: tag
      run: |
        # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
        TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
        git push origin $TAG
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: vm-manager-client
        tag_name: ${{ steps.tag.outputs.tag }}
